name: Windows-RDP
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Descargar Ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
      - name: Autenticar
        run: .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      - name: Activar RDP y Usuario
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin P@ssw0rd! /add
          net localgroup administrators runneradmin /add
      - name: Iniciar Ngrok
        run: |
          Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp --region us 3389"
      - name: Ver Direccion en Consola
        run: |
          Start-Sleep -Seconds 15
          Invoke-RestMethod http://localhost:4040/api/tunnels | Select-Object -ExpandProperty tunnels | Select-Object -ExpandProperty public_url
      - name: Mantener Vivo
        run: |
          Write-Host "Si no ves nada en la web de Ngrok, mira el paso anterior 'Ver Direccion en Consola'"
          Start-Sleep -Seconds 21600
